import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                'on-error': '#ffefee',
                'on-secondary-fixed': '#00480f',
                'primary-fixed-dim': '#2498f5',
                'inverse-primary': '#2498f5',
                'primary-dim': '#00528b',
                'secondary-dim': '#005d16',
                'on-tertiary-fixed-variant': '#6a6000',
                'surface-container-lowest': '#ffffff',
                'surface-variant': '#d9dde1',
                'secondary-fixed-dim': '#83e881',
                error: '#b31b25',
                'surface-tint': '#005e9f',
                'outline-variant': '#abadb0',
                'secondary-container': '#91f78e',
                'on-secondary-fixed-variant': '#00691a',
                'on-error-container': '#570008',
                'surface-dim': '#d0d5d9',
                'primary-container': '#44a5ff',
                primary: '#005e9f',
                'tertiary-container': '#ffeb3b',
                secondary: '#006b1b',
                'on-secondary': '#d1ffc8',
                'secondary-fixed': '#91f78e',
                'on-secondary-container': '#005e17',
                outline: '#74777a',
                'on-primary': '#edf3ff',
                'inverse-on-surface': '#9a9da0',
                'surface-container-highest': '#d9dde1',
                'on-surface-variant': '#595c5e',
                'on-tertiary-container': '#5f5600',
                'tertiary-dim': '#595000',
                'on-primary-fixed': '#000000',
                tertiary: '#665c00',
                'tertiary-fixed': '#ffeb3b',
                'on-background': '#2c2f32',
                'error-container': '#fb5151',
                'tertiary-fixed-dim': '#f0dc2b',
                'inverse-surface': '#0b0f11',
                background: '#f5f7fa',
                'surface-container': '#e5e8ec',
                'on-tertiary-fixed': '#4b4400',
                'surface-container-high': '#dfe3e7',
                'error-dim': '#9f0519',
                'on-primary-fixed-variant': '#002e51',
                'on-primary-container': '#002442',
                'on-tertiary': '#fff4b0',
                'surface-bright': '#f5f7fa',
                'on-surface': '#2c2f32',
                'primary-fixed': '#44a5ff',
                'surface-container-low': '#eef1f4',
                surface: '#f5f7fa',
            },
            borderRadius: {
                DEFAULT: '1rem',
                lg: '2rem',
                xl: '3rem',
            },
            fontFamily: {
                sans: ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                headline: ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                body: ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                label: ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [forms],
};
